baseURL = "https://letusseng.github.io/"
languageCode = "en-us"
title = "Seng Ye Xiong"
theme = "gokarna"

[params]
  avatarAltText = "avatar"
  avatarSize = "size-m"
  avatarURL = "/images/avatar.jpg"
  description = "I can't remember things as well as I used to..."
  footer = "LetUsSeng"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<span data-feather='home'></span>"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

#   [[menu.main]]
#     name = "Projects"
#     pre = "<span data-feather='code'></span>"
#     url = "/projects/"
#     weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/LetUsSeng/letusseng.github.io"
    weight = 5

  [[menu.main]]
    identifier = "rss"
    pre = "<span data-feather='rss'></span>"
    url = "/index.xml"
    weight = 7

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4
    ordered = false

[minify]
    minifyOutput = true
